source 'https://rubygems.org'

gem 'rails',            '4.2.4'
gem 'pg'
gem 'sass-rails',       '~> 5.0'
gem 'uglifier',         '>= 1.3.0'
gem 'coffee-rails',     '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder',         '~> 2.0'
gem 'sdoc',             '~> 0.4.0', group: :doc
gem 'pry-rails'
gem 'annotate'
gem 'bcrypt'

# React and Flux resources
gem 'react-rails',      '1.3.0'
gem 'flux-rails-assets'

group :development do
  gem 'pry'
  gem 'byebug'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'spring'
  gem 'web-console',    '~> 2.0'
end

group :test do
  gem 'capybara'
  gem 'jasmine',        '~> 2.0.0.rc4'
  gem 'rspec-rails',    '~> 3.0'
end

group :development, :test do
  gem 'launchy'
end
